### ISSUE TITLE
syntax error when get EDAC_TYPE

### ISSUE THREAD

**Issue by cdkey** [andikleen/mce-test#4]
commit 533f091f0eed ("mce-test: Unload possible EDAC drivers to avoid interference.") cause a syntax error, and the scripts are broken with:

```
syntax error near unexpected token `elif'
```

**Comment by aegl** [comment]
This might have been fixed by a different version of that commit that was applied to another mce-test tree:

git://git.kernel.org/pub/scm/utils/cpu/mce/mce-test.git

**Comment by cdkey** [comment]
yes, confirm solved, thanks
